name: Go CD Pipeline

on:
  workflow_run:
    workflows: ["Go CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: echo "🖥️ Test self hosted runner on my machine"
      - name: Checkout
        uses: actions/checkout@v4

    #   - name: ssh to server
    #     uses: webfactory/ssh-agent@v0.9.0
    #     with: |
    #         ssh-private-key: ${{ secret.SSH_PRIVATE_KEY}}
      - name: Clone Repo 
        run: |
            git clone https://github.com/kevinavicenna/product-go-postgresql.git || (cd product-go-postgresql && git pull)
            cd product-go-postgresql
            ls

    #   - name:  Test Run docker-compose
    #     uses: hoverkraft-tech/compose-action@v2.0.1
    #     with:
    #       compose-file: "./Docker-compose.yaml"

      - name: Build and Start Docker Compose
        run: |
          ls
          docker compose -f Docker-compose.yaml down || true
          docker compose -f Docker-compose.yaml up -d
      - name: Verify Deployment
        run: |
            docker ps

    #   - name: Docker Push
    #     run: |
    #         docker pull ${{ secrets.DOCKER_USERNAME }}/product-go-postgresql:latest
    #   - name: delete old container
    #     run: | 
    #         docker stop product-go-postgresql:latest || true
    #         docker rm product-go-postgresql:latest || true
    #   - name: Run container
    #     run: |
    #         docker run -p 8080 ${{ secrets.DOCKER_USERNAME }}/product-go-postgresql:latest
