# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: go mod tidy

    - name: Build the application
      run: |
        echo "Building the Go application..."
        go build -o testing main.go
        
    # - name: Run tests
    #   run: |
    #     echo "Running tests..."
    #     go test -v ./...
        
  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        
    - name: Install dependencies
      run: go mod download
      
    - name: Build application
      run: go build -o testing ./main.go 

    # - name: Set up SSH
    #   uses: webfactory/ssh-agent@v1
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl stop myapp || true

          mkdir -p ~/testing
          rm -rf ~/testing/*
          scp -r testing ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/testing/

          cd ~/testing
          sudo systemctl start testing
